apiVersion: apps/v1
kind: Deployment
metadata:
  name: opuyt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opuyt
  template:
    metadata:
      labels:
        app: opuyt
    spec:
      containers:
      - image: okteto.dev/opuyt:latest
        name: opuyt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "067e1612-2bdf-498c-b9e3-cc0be192f177"
        - name: Vless_Path
          value: "/vlaassd32et"
        - name: Vmess_UUID
          value: "067e1612-2bdf-498c-b9e3-cc0be192f177"
        - name: Vmess_Path
          value: "/vmqsfghtQ"
        - name: Share_Path
          value: "/v2link"
