apiVersion: apps/v1
kind: Deployment
metadata:
  name: opuyt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opuyt
  template:
    metadata:
      labels:
        app: opuyt
    spec:
      containers:
      - image: okteto.dev/opuyt:latest
        name: opuyt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "f491b0a1-4e72-45f6-8884-92c733f195de"
        - name: Vless_Path
          value: "/vlaassd32et"
        - name: Vmess_UUID
          value: "f491b0a1-4e72-45f6-8884-92c733f195de"
        - name: Vmess_Path
          value: "/vmqsfghtQ"
        - name: Share_Path
          value: "/v2link"
