apiVersion: apps/v1
kind: Deployment
metadata:
  name: bananbgd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bananbgd
  template:
    metadata:
      labels:
        app: bananbgd
    spec:
      containers:
      - image: okteto.dev/bananbgd:latest
        name: bananbgd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "4bc137b7-3da6-49ed-a1a4-bb2da42dbda8"
        - name: Vless_Path
          value: "/vlaassd32et"
        - name: Vmess_UUID
          value: "4bc137b7-3da6-49ed-a1a4-bb2da42dbda8"
        - name: Vmess_Path
          value: "/vmqsfghtQ"
        - name: Share_Path
          value: "/v2link"
